server:
  port : 8399
  
# Oracle Connect
spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/traveldb?serverTimezone=Asia/Seoul&&allowMultiQueries=true
    url: jdbc:log4jdbc:mysql://localhost:3306/traveldb?serverTimezone=Asia/Seoul&&allowMultiQueries=true
    username: travel
    password: tiger
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    
  devtools: 
    livereload:
      enabled: true

  # Jpa Setting
  jpa:  
    hibernate:
      ddl-auto: none  #none create update
    properties: 
      hibernate: 
        default_batch_fetch_size: 500 
      show_sql:   true    # System.out 에 하이버네이트 실행 SQL
      format_sql: true

  # view Resolver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  # gmail Transfer
  mail: 
    host: smtp.gmail.com
    port: 587
    username: lswhy8120@gmail.com
    password: myjbpfbbreulnwin
    properties: 
      mail: 
       smtp:
        auth: true
        starttls.enable: true
  servlet:
    multipart: 
      max-file-size: 10MB
      max-request-size: 10MB
      
# Mybatis
mybatis: 
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mappers/*.xml
            
logging.level:
  web: info
  sql: off
  jdbc: off
  jdbc.sqlonly: off
  jdbc.sqltiming: info
  jdbc.resultsettable: info
  org.hibernate.SQL: off   # logger를 통해 하이버네이트 실행 SQL